baseurl = "http://droxer.github.io/blog"
languageCode = "en-us"
title = "Constantly Thinking"
theme = "purehugo"
disqusShortname = "droxer"
UA-71396024-1

[params]
  githubName = "droxer"
  google_analytics = "UA-71396024-1"
