baseurl = "http://blog.droxer.me"
languageCode = "en-us"
title = "Distributed Thinking"
theme = "purehugo"
disqusShortname = "droxer"

[params]
  githubName = "droxer"
  linkedinName = "droxer"
  google_analytics = "UA-71396024-1"
