baseurl = "http://blog.droxer.me"
languageCode = "en-us"
title = "Distributed Thinking"
theme = "pixyll"
contentdir = "content"
publishdir = "public"



[indexes]
    tag = "tags"
[params]
  search_engine = true
  google_analytics_id= "UA-71396024-1"
  paginate = true
  disqus_Shortname = "droxer"
